# Generated by Django 6.0.5 on 2026-05-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_1000',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_750',
        ),
    ]
